server:
  port: 9000

spring:
  application:
    name: demo

  datasource:
    platform: mysql
    url: jdbc:mysql://netflix.cjm9rym2cdtv.ap-northeast-2.rds.amazonaws.com/netflix?autoReconnect=true # 변경해주세요
    username: ksy # 변경해주세요
    password: gintama # 변경해주세요
    # driver-class-name: com.mysql.cj.jdbc.Driver # mysql 8버전
    driver-class-name: com.mysql.jdbc.Driver # mysql 5버전